import { Manrope } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav"
import Footer from "./components/Footer";
import { CartProvider } from "./context/CartContext";

const manrope = Manrope({
  subsets: ["latin"],
});



export const metadata = {
  title: "Audiophile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={manrope.className}
      >
        <Nav />
        <main>
          <CartProvider>{children}</CartProvider>
        </main>
        <Footer />
      </body>
    </html>
  );
}
